# OpenAI Codex CLI — {{PROJECT_NAME}}

Forge targets **OpenAI Codex CLI** using **`AGENTS.md`** as the primary project instruction file (same portable root context as other tools).

## Read order (verify in current OpenAI docs)

Codex typically walks from the repository root toward the working directory and merges instruction files. Common precedence at each level includes overrides before base names; see [Codex customization](https://developers.openai.com/codex/concepts/customization/) and [AGENTS.md guide](https://developers.openai.com/codex/guides/agents-md/).

## This repo

- **Authoritative pack context:** root **`AGENTS.md`** (generated by forge).
- **Optional skills (forge):** when selected in the installer, bundles live under **`docs/forge-skills/codex/forge-<skill-id>/SKILL.md`** and **`workflow.md`** (Agent Skills–style; extend or replace in-repo).
- Optional **oh-my-codex (OMX)** is a **separate runtime** layer — not a second forge adapter. See **docs/FORGE-OMX-COMPANION.md**.

---

*Generated {{DATE_ISO}} by forge-vibe.*
